<a href="https://colab.research.google.com/github/erickson1999/big-data/blob/main/Numpy_ejercicos_23_04_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Importar NumPy:**

In [72]:
import numpy as np

**1. Creación de Arrays:**
*   Crea un array unidimensional (vector) con 5 elementos enteros de tu
elección.
*   Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores
enteros consecutivos.
*   Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena
de ceros.
*   Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena
de unos.
*   Utiliza la función np.random.randint() para crear una matriz.











In [73]:
# Crea un array unidimensional (vector) con 5 elementos enteros de tu
# elección.
a1 = np.array([1,2,3,4,5])
print("matriz unidimensional: ",a1)
# Crea una matriz bidimensional (matriz) de tamaño 3x3 con valores
# enteros consecutivos.
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("matriz bidimensional 3x3: ",a2)
# Utiliza la función np.zeros() para crear una matriz de tamaño 2x4 llena de ceros
a3 = np.zeros((2,4),int)
print("matriz ceros: ",a3)
# Utiliza la función np.ones() para crear una matriz de tamaño 3x2 llena de unos.
a4 = np.ones((3,2),int)
print("matriz unos: ", a4)
# Utiliza la función np.random.randint() para crear una matriz.
a5 = np.random.randint(1,4,size=(3,3))
print("matriz aleatoria 3x3: ",a5 )

matriz unidimensional:  [1 2 3 4 5]
matriz bidimensional 3x3:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
matriz ceros:  [[0 0 0 0]
 [0 0 0 0]]
matriz unos:  [[1 1]
 [1 1]
 [1 1]]
matriz aleatoria 3x3:  [[2 3 1]
 [2 2 2]
 [1 3 2]]


**2. Acceso a Elementos:**
* Accede al tercer elemento del vector creado en el paso 2.
* Accede al elemento en la segunda fila y segunda columna de la matriz
creada en el paso 2.

In [74]:
# Accede al tercer elemento del vector creado en el paso 2.
ele3 = a1[2]
print("tercer elemento: ", ele3)
# Accede al elemento en la segunda fila y segunda columna de la matriz creada en el paso 2
ele2x2 = a2[2][2]
print("elemento 2x2: ", ele2x2)


tercer elemento:  3
elemento 2x2:  9


**3. Propiedades de los Arrays:**
* Utiliza el atributo ndim para verificar la cantidad de dimensiones de la
matriz creada en el paso 2.
* Utiliza el atributo shape para obtener la forma de la matriz creada en el
paso 2.
* Utiliza el atributo size para obtener el tamaño total de la matriz creada
en el paso 2.

In [75]:
# Utiliza el atributo ndim para verificar la cantidad de dimensiones de la matriz creada en el paso 2.
d1 = a1.ndim
print("ndim: ",d1)
# Utiliza el atributo shape para obtener la forma de la matriz creada en el paso 2.
d2 = a1.shape
print("shape: ",d2)
# Utiliza el atributo size para obtener el tamaño total de la matriz creada en el paso 2
d3 = a1.size
print("size: ",d3)

ndim:  1
shape:  (5,)
size:  5


**4. Operaciones Básicas:**
* Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
* Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
* Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2,
utilizando tanto la división por elementos como la multiplicación por la
inversa.

In [76]:
# Suma dos matrices de tamaño 2x2 con valores aleatorios entre 0 y 10.
ale1 = np.random.randint(0,10,size=(2,2))
ale2 = np.random.randint(0,10,size=(2,2))
print("Suma matriz aleatoria 2x2: ",ale1+ale2)
# Multiplica dos matrices de tamaño 3x2 y 2x3 respectivamente.
ale3 = np.random.randint(1,10,size=(3,2))
ale4 = np.random.randint(1,10,size=(2,3))
print("Producto matrices 3x2 2x3 aleatorias: ", ale3*ale4.shape)
# Divide una matriz de tamaño 2x2 por otra matriz de tamaño 2x2, utilizando tanto la división por elementos como la multiplicación por la inversa.
ale5= np.random.randint(1,10,size=(2,2))
ale6= np.random.randint(1,10,size=(2,2))

print("División por elementos: ",ale5/ale6)
print("División matemática: ", ale5 * np.linalg.inv(ale6))

Suma matriz aleatoria 2x2:  [[ 8 14]
 [14 17]]
Producto matrices 3x2 2x3 aleatorias:  [[14  3]
 [12 21]
 [18  9]]
División por elementos:  [[0.71428571 1.8       ]
 [2.         0.28571429]]
División matemática:  [[ 1.20689655 -1.55172414]
 [-1.10344828  0.48275862]]


**5. Manipulación de Arrays:**
* Utiliza la función reshape() para convertir el vector creado en el paso 2
en una matriz de tamaño 9x1
.
* Utiliza la función flatten() para convertir la matriz creada en el paso 2
en un vector unidimensional.

In [77]:
# Utiliza la función reshape() para convertir el vector creado en el paso 2 en una matriz de tamaño 9x1.
re = np.reshape(a2,(9,1))
print("matriz 9x1 reshape: ", re)
# Utiliza la función flatten() para convertir la matriz creada en el paso 2 en un vector unidimensional.
fla = a2.flatten()
print("matriz aplanada flatten: ",fla)

matriz 9x1 reshape:  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
matriz aplanada flatten:  [1 2 3 4 5 6 7 8 9]


**6. Operaciones Estadísticas:**
* Calcula la suma de todos los elementos de la matriz creada en el paso 2.
* Calcula la media de cada fila de la matriz creada en el paso 2.

In [78]:
# Calcula la suma de todos los elementos de la matriz creada en el paso 2.
sum = np.sum(a2)
print("Suma de elementos: ", a2)
# Calcula la media de cada fila de la matriz creada en el paso 2.
media = np.mean(a2,axis=1)
print("Media de cada fila: ", media)

Suma de elementos:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Media de cada fila:  [2. 5. 8.]


**7. Indexación y Rebanado:**
* Imprime la primera fila de la matriz creada en el paso 2.
* Imprime las primeras dos columnas de la matriz creada en el paso 2.

In [79]:
#  Imprime la primera fila de la matriz creada en el paso 2.
fil1 = a2[0]
print("Primera fila: ", fil1)
#  Imprime las primeras dos columnas de la matriz creada en el paso 2.
col2 = a2[:, :2]
print("Primeras 2 columnas: ", col2)

Primera fila:  [1 2 3]
Primeras 2 columnas:  [[1 2]
 [4 5]
 [7 8]]


**8. Ejercicio Adicional:**
* Define una matriz de tamaño 4x4 con valores aleatorios.
* Escribe un código para encontrar el valor máximo y mínimo de la matriz,
así como su posición.

In [80]:
# Define una matriz de tamaño 4x4 con valores aleatorios.
m4x4 = np.random.randint(1,99,size=(4,4))
print("Matriz 4x4 aleatoria: ", m4x4)
# Escribe un código para encontrar el valor máximo y mínimo de la matriz, así como su posición.

def max(arra):
  max = -99999999999999999
  for i in arra:
    for e in i:
      if(e > max):
        max = e
  return max

def min(arra):
  min = 9999999999999999999
  for i in arra:
    for e in i:
      if(e < min):
        min = e
  return min

print("Número máximo de array: ",max(m4x4))

print("Número mínimo de array: ",min(m4x4))

Matriz 4x4 aleatoria:  [[72 59 39 20]
 [30 36 90 13]
 [92 56 39 71]
 [73 86  5 98]]
Número máximo de array:  98
Número mínimo de array:  5
